tests: fix build failure with too short char array
The test test_unknown_opnum_decode() triggers a build failure with GCC
version 15.2.0:

  /home/pnfs/pnfscore/tests/unit/test_xdr_codec.c: In function ‘test_unknown_opnum_decode’:
  /home/pnfs/pnfscore/tests/unit/test_xdr_codec.c:1899:24: error: initializer-string for array of ‘char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (5 chars into 4 available) [-Werror=unterminated-string-initialization]
   1899 |         char ttag[4] = "test";
        |                        ^~~~~~

The character array ttag is later used as opaque binary data, not as a
string, so there's no need for it to be NUL-terminated.

Initializing the variable as an array of 4 characters instead of as a
string fixes the build failure.